### ISSUE TITLE
`src/TimeScaleUtilities/Wait.lua` can be optimized heavily

### ISSUE THREAD

**Issue by lucasmz-dev** [CadeusTheGreat/TimeScaleFramework#2]
*Note: This suggestion might not be possible, make sense, etc. I'm not a user of this library, I just found some stuff when working on making the repo Rojo friendly and found I should give possible suggestions on changing things I, at first look, believe should be changed.*

The first thing when working on turning this into Rojo-friendly was the Wait module, and it can be heavily improved.

* Wait uses `HttpService:GenerateGUID()` which is extremely expensive to call.

* It uses a bindable to yield and resume threads. 
* TimeElapsed is written to every Heartbeat.

* Calls `:GetAttribute("TimeScale")` for every yield being checked. (This seems to be an issue on its own on most scripts, I plan on filling a report on a better solution for this overall)

Using `table.insert` would be a better solution than using `:GenerateGUID`, but better yet is using a linked list which solves a bunch of other issues. Using a linked list is more complex.

For resuming / yielding threads, ever since the task library was launched, doing that yourself is easy with `coroutine.running()` and `task.spawn()` and way faster than using a bindable to do that.

For TimeElapsed calculation, I prefer to have a local in the top with the number of seconds passed, that's set to every frame, anyway, as you'll see below how that's implemented in BetterWait.

And for the TimeScale handling, like I said it's an unique case that has a unique solution that would be applied in this case, and would have minimal performance penalties.

A lot of what I talk about here is used on my [BetterWait](https://github.com/LucasMZReal/BetterWait) implementation, and you can use it to implement your wait function.

**Comment by CadeusTheGreat** [comment]
Changes have been made, let me know if there's anything else I can do to optimise the wait function otherwise I'll close this issue. 😄
