### ISSUE TITLE
Cache `:GetService` calls

### ISSUE THREAD

**Issue by lucasmz-dev** [CadeusTheGreat/TimeScaleFramework#5]
The codebase right now has a lot of  `:GetService` calls, usually for the exact same service. 

`:GetService` is not necessarily a fast call to make, and it is usually cached into a local that has the name of the service. 
This should definitely be looked into! I can make a pull request to do that myself actually.

**Comment by CadeusTheGreat** [comment]
I'm more than happy to make this change if you'd like me to. Let me know if you'd like to do this one or me. 😃

**Comment by CadeusTheGreat** [comment]
@LucasMZReal Made the changes to the pull request, let me know if there's any other changes to make for this issue otherwise I'll close it.

**Comment by LucasMZReal** [comment]
@CadeusTheGreat seems good! 👍🏻
